#!/bin/sh
set -e

if [ "$1" = "upgrade" ] || [ "$1" = "install" ]; then
  if command -v systemctl >/dev/null 2>&1; then
    systemctl stop p2premote-service.service >/dev/null 2>&1 || true
  fi
fi

exit 0
